steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'prod-project-docker.pkg.dev/prod-project-402708/notes-app/notes-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'prod-project-docker.pkg.dev/prod-project-402708/notes-app/notes-app']
images: 
- prod-project-docker.pkg.dev/prod-project-402708/notes-app/notes-app
options:
  logsBucket: 'gs://cloud_build_ogs'


